FROM ubuntu:18.04

ARG APP_DIR=app
RUN mkdir -p ${APP_DIR}
WORKDIR ${APP_DIR}

RUN apt update
RUN apt install nodejs npm nginx
RUN systemctl enable nginx

COPY . .
RUN npm install --production
RUN npm build

RUN mkdir -p /var/www/ssb/
RUN mv ./dist/* /var/www/ssb/
RUN mv ./ssb.conf /etc/nginx/sites-available/ssb.conf
RUN ln -s /etc/nginx/sites-available/ssb.conf /etc/nginx/sites-enabled/ssb.conf
RUN nginx -s reload

