FROM ubuntu:18.04

ARG APP_DIR=app
RUN mkdir -p ${APP_DIR}
WORKDIR ${APP_DIR}

RUN apt update
RUN apt install curl -y

RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -

RUN apt update
RUN apt install nodejs nginx -y

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

RUN mkdir -p /var/www/ssb/
RUN mv ./dist/* /var/www/ssb/
RUN mv ./ssb.conf /etc/nginx/sites-available/ssb.conf
RUN ln -s /etc/nginx/sites-available/ssb.conf /etc/nginx/sites-enabled/ssb.conf


