version: "3.7"
services:
  frontend:
    image: sfront
    build: ./frontend
    command: nginx -g 'daemon off;'
    ports:
      - 8080:80
    restart: always
    depends_on:
      - backend

  backend:
    image: sbackend
    build: ./backend
    ports:
      - 8000:8000
    command: php -S 0.0.0.0:8000
    restart: always
